[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
reqwest = {version = "0.12.11", features = ["zstd", "rustls-tls-manual-roots"]}
sha2 = "0.10.8"
tokio = {version ="1.42.0", features = ["macros", "fs", "rt-multi-thread"]}
